import { SHOHID_PROFILE } from "@/lib/ai";
import { GoogleGenAI } from "@google/genai";
import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const { tool, input } = await req.json();

    if (!input || typeof input !== "string") {
      return NextResponse.json(
        { error: "Input is required." },
        { status: 400 }
      );
    }

    const apiKey = process.env.GEMINI_API_KEY;

    if (tool === "code-explainer") {
      if (apiKey) {
        try {
          const ai = new GoogleGenAI({ apiKey });
          const prompt = `You are a senior software architect. Analyze and break down the following code snippet. Explain what it does line-by-line, point out any performance or security issues, and suggest modern optimizations:\n\n\`\`\`\n${input}\n\`\`\``;
          const res = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: [{ role: "user", parts: [{ text: prompt }] }],
          });
          if (res.text) return NextResponse.json({ result: res.text });
        } catch (e) {
          console.warn("AI Lab Gemini call failed, using fallback:", e);
        }
      }

      // Fallback response
      const fallbackResult = `### 🔍 AI Code Breakdown\n\n` +
        `**Overview:** The provided code snippet appears to handle asynchronous data flow or state mutations.\n\n` +
        `**Line-by-Line Highlights:**\n` +
        `- **Data Inputs:** Accepts dynamic state properties and executes callback hooks.\n` +
        `- **Performance:** Clean execution, consider memoization (\`useMemo\` / \`useCallback\`) if executed frequently during rendering.\n` +
        `- **Best Practices:** Strong TypeScript typing ensures type safety across render cycles.\n\n` +
        `💡 *Tip: Powered by Shohid AI Intelligence Core!*`;

      return NextResponse.json({ result: fallbackResult });
    }

    if (tool === "product-architect") {
      if (apiKey) {
        try {
          const ai = new GoogleGenAI({ apiKey });
          const prompt = `You are a Principal Systems Architect. Take this product/app idea: "${input}". Provide a clean architectural blueprint including:\n1. Tech Stack (Frontend, Backend, Database, Realtime/Caching)\n2. High-Level System Architecture Flow\n3. Suggested Database Data Models\n4. Recommended Key API Endpoints\n5. Scalability & Security considerations.`;
          const res = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: [{ role: "user", parts: [{ text: prompt }] }],
          });
          if (res.text) return NextResponse.json({ result: res.text });
        } catch (e) {
          console.warn("AI Lab Gemini call failed, using fallback:", e);
        }
      }

      const fallbackResult = `### 🏗️ Product Blueprint: "${input}"\n\n` +
        `#### 1. Tech Stack Recommendations\n` +
        `- **Frontend:** Next.js 16 (App Router), React 19, Tailwind CSS v4, Framer Motion\n` +
        `- **Backend & API:** Node.js / NestJS or Next.js Route Handlers + WebSockets\n` +
        `- **Database & Cache:** PostgreSQL (Prisma/Drizzle ORM) + Redis for caching & rate limiting\n` +
        `- **Deployment:** Vercel / Cloudflare Workers + Docker on GCP\n\n` +
        `#### 2. Key Modules & Endpoints\n` +
        `- \`POST /api/auth/session\` - User Authentication & JWT payload\n` +
        `- \`GET /api/v1/resource\` - Paginated resource list with caching\n` +
        `- \`WS /ws/realtime\` - Bi-directional updates via WebSockets\n\n` +
        `💡 *Tip: Generated by Shohid AI Architecture Core!*`;

      return NextResponse.json({ result: fallbackResult });
    }

    if (tool === "recruiter-matcher") {
      if (apiKey) {
        try {
          const ai = new GoogleGenAI({ apiKey });
          const prompt = `You are an executive talent matcher. Compare the following Job Description (JD) with Shohid's profile:\n\nShohid's Profile:\n- Role: ${SHOHID_PROFILE.role}\n- Bio: ${SHOHID_PROFILE.bio}\n- Skills: ${SHOHID_PROFILE.skills.join(", ")}\n- Projects: ${SHOHID_PROFILE.projects.map(p => p.name + " (" + p.tech + ")").join("; ")}\n\nJob Description:\n"${input}"\n\nGenerate:\n1. Match Score (percentage e.g. 92% Match)\n2. Key Matching Strengths\n3. Recommended Project Examples to Highlight\n4. Tailored Cover Message/Pitch from Shohid.`;
          const res = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: [{ role: "user", parts: [{ text: prompt }] }],
          });
          if (res.text) return NextResponse.json({ result: res.text });
        } catch (e) {
          console.warn("AI Lab Gemini call failed, using fallback:", e);
        }
      }

      const fallbackResult = `### 🎯 Recruiter Match Analysis\n\n` +
        `**Match Score:** 🌟 **94% Match** for Senior Frontend / Full-Stack Engineer roles!\n\n` +
        `**Key Matching Strengths:**\n` +
        `- ✅ Expert proficiency in **Next.js 16**, **React 19**, **TypeScript**, and **Tailwind CSS**.\n` +
        `- ✅ Production experience with **Real-time WebSockets** (FleetOS, Model Boss Offers, Game Arena X).\n` +
        `- ✅ Proven leadership as **Project Lead** managing complex multi-tenant dashboards.\n\n` +
        `**Suggested Pitch to Hiring Manager:**\n` +
        `*"Hi! Based on your job description, Shohid's track record in building high-concurrency real-time Next.js applications and scalable UI design systems aligns seamlessly with your team's requirements."*`;

      return NextResponse.json({ result: fallbackResult });
    }

    return NextResponse.json({ error: "Invalid tool specified." }, { status: 400 });
  } catch (error) {
    console.error("Error in /api/ai-lab route:", error);
    return NextResponse.json(
      { error: "Failed to process AI Lab request." },
      { status: 500 }
    );
  }
}
